remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
excerpt_separator: <!--more-->
locale: "en-US"
title: "Second Sleep"
name: "Blaine Perry"
description: "Azure consulting services"
repository: 2ndsleep/2ndsleep.github.io
url: "https://www.secondsleep.io"
masthead_title: "Second Sleep"
author:
  name: "Blaine Perry"
  location: "Asheville, NC"
  bio: "Cloud architect with over 85 years of Azure experience"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-58PR5VHWK0"
atom_feed:
  hide: true
fake_company_name: "Scramoose"
permalink: /:categories/:title

collections:
  service_categories:
    output: true
    permalink: /:categories
  services:
    output: true
    permalink: /:categories

include: ["_pages"]

breadcrumbs: true
breadcrumb_home_url: /learn
breadcrumb_home_label: Learn

defaults:
  - scope:
      path: ""
      type: service_categories
    values:
      layout: service_category
      page_type: service_category
  - scope:
      path: ""
      type: services
    values:
      layout: service
      page_type: service
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      page_type: post
      read_time: true
      author_profile: true
      toc_icon: cloud
      toc_sticky: true

plugins:
  - jekyll-include-cache
  - jemoji