remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
excerpt_separator: <!--more-->
locale: "en-US"
title: "Second Sleep"
name: "Blaine Perry"
description: "Azure consulting services"
repository: 2ndsleep/2ndsleep.github.io
url: "https://www.secondsleep.io"
masthead_title: "Second Sleep"
author:
  name: "Blaine Perry"
  location: "Asheville, NC"
  bio: "Cloud architect with an irrational affinity for Azure"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/blaine-perry-second-sleep"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/2ndsleep"
    - label: "info@secondsleep.io"
      icon: "fa-solid fa-envelope"
      url: "mailto:info@secondsleep.io"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-58PR5VHWK0"
atom_feed:
  hide: true
permalink: /:categories/:title

collections:
  service_categories:
    output: true
    permalink: /:categories
  services:
    output: true
    permalink: /:categories

include: ["_pages"]

breadcrumbs: true
breadcrumb_home_url: /learn
breadcrumb_home_label: Learn

comments:
  provider: "giscus"

defaults:
  - scope:
      path: ""
      type: service_categories
    values:
      layout: service_category
      page_type: service_category
  - scope:
      path: ""
      type: services
    values:
      layout: service
      page_type: service
  - scope:
      path: ""
      type: posts
    values:
      layout: secondsleep_single
      page_type: post
      read_time: true
      author_profile: true
      toc_icon: cloud
      toc_sticky: true
      comments:
        provider: "giscus"
        giscus:
          repo_id          : "MDEwOlJlcG9zaXRvcnkyNzA2Nzc5MzE="
          category_name    : "Blog Comments"
          category_id      : "DIC_kwDOECI3q84CcOVw"
          discussion_term  : "og:title"
          reactions_enabled: 1
          theme            : "light"
  - scope:
      path: "*/learn/*"
      type: posts
    values:
      toc: true

plugins:
  - jekyll-include-cache
  - jemoji
  - jekyll-sitemap