remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
excerpt_separator: <!--more-->
locale: "en-US"
title: "Second Sleep"
subtitle: "<i>Automating your way to success!</i>"
name: "Blaine Perry"
description: "A blog for using a DevOps approach to IT."
url: "https://www.secondsleep.net"
masthead_title: "Second Sleep"
logo: "/assets/images/logos/secondsleep/88x88.png"
author:
  name: "Blaine Perry"
  location: "Asheville, NC"
  bio: "Systems architecture with over 25 years of Azure cloud experience"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-58PR5VHWK0"  
collections:
  services:
    output: true
  procedures:
    output: true

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: procedures
    values:
      layout: procedure
  - scope:
      path: ""
      type: services
    values:
      layout: service
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true


plugins:
  - jekyll-include-cache
