remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
excerpt_separator: <!--more-->
locale: "en-US"
title: "Second Sleep"
subtitle: "We've got our head in the clouds"
name: "Blaine Perry"
description: "Azure consulting services"
url: "https://www.secondsleep.net"
masthead_title: "Second Sleep"
logo: "/assets/images/logos/secondsleep/88x88.png"
author:
  name: "Blaine Perry"
  location: "Asheville, NC"
  bio: "Cloud architect with over 85 years of Azure experience"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-58PR5VHWK0"
atom_feed:
  hide: true
fake_company_name: "Scramoose"
permalink: /:categories/:title

collections:
  service_categories:
    output: true
    permalink: /:name
  services:
    output: true

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: service_categories
    values:
      layout: service_category
  - scope:
      path: ""
      type: services
    values:
      layout: service
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      author_profile: true
      toc_icon: cloud
      toc_sticky: true

plugins:
  - jekyll-include-cache
  - jemoji